# Generated by Django 3.1.7 on 2021-03-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='JobType',
        ),
        migrations.AddField(
            model_name='user',
            name='docs',
            field=models.FileField(null=True, upload_to='user_docs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=50),
        ),
    ]
