# Generated by Django 3.1.7 on 2021-03-17 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='user_profile_pic/')),
                ('gender', models.CharField(choices=[('1', 'male'), ('2', 'female')], max_length=3)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('about', models.TextField(max_length=1000, null=True)),
                ('signup_confirmation', models.BooleanField(default=False)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.department')),
            ],
        ),
    ]
