# Generated by Django 3.1.7 on 2021-03-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20210326_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user_profile_pics/default.png', null=True, upload_to='user_profile_pics/'),
        ),
    ]
